blank_issues_enabled: true
contact_links:
  - name: Matrix Chat
    url: https://matrix.to/#/#jupiterweb:jupiterbroadcasting.com
    about: Our base of operations for group discussions on this project is our Matrix chat room
